package models

import (
	"bbs/db"
)

func nav_init() {
	model := new(Model)
	c, _ := model.Table("Common_nav").Count()
	if c == 0 {
		var data = make([]*db.Common_nav, 45)
		data[0] = &db.Common_nav{Id: 1, Parentid: 0, Name: "门户", Title: "Portal", Url: "portal.php", Identifier: "1", Target: 0, Type: 0, Available: 1, Displayorder: 1, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[1] = &db.Common_nav{Id: 2, Parentid: 0, Name: "论坛", Title: "BBS", Url: "forum.php", Identifier: "2", Target: 0, Type: 0, Available: 1, Displayorder: 2, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[2] = &db.Common_nav{Id: 3, Parentid: 0, Name: "群组", Title: "Group", Url: "group.php", Identifier: "3", Target: 0, Type: 0, Available: -1, Displayorder: 7, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[3] = &db.Common_nav{Id: 4, Parentid: 0, Name: "动态", Title: "Space", Url: "home.php", Identifier: "4", Target: 0, Type: 0, Available: -1, Displayorder: 8, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[4] = &db.Common_nav{Id: 5, Parentid: 0, Name: "插件", Title: "Plugin", Url: "#", Identifier: "6", Target: 0, Type: 0, Available: 1, Displayorder: 9, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[5] = &db.Common_nav{Id: 6, Parentid: 0, Name: "帮助", Title: "Help", Url: "misc.php?mod=faq", Identifier: "7", Target: 0, Type: 0, Available: 0, Displayorder: 10, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[6] = &db.Common_nav{Id: 7, Parentid: 0, Name: "排行榜", Title: "Ranklist", Url: "misc.php?mod=ranklist", Identifier: "8", Target: 0, Type: 0, Available: -1, Displayorder: 16, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[7] = &db.Common_nav{Id: 8, Parentid: 0, Name: "广播", Title: "Follow", Url: "home.php?mod=follow", Identifier: "9", Target: 0, Type: 0, Available: 0, Displayorder: 5, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[8] = &db.Common_nav{Id: 9, Parentid: 0, Name: "导读", Title: "Guide", Url: "forum.php?mod=guide", Identifier: "10", Target: 0, Type: 0, Available: -1, Displayorder: 3, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[9] = &db.Common_nav{Id: 10, Parentid: 0, Name: "淘帖", Title: "Collection", Url: "forum.php?mod=collection", Identifier: "11", Target: 0, Type: 0, Available: 1, Displayorder: 11, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[10] = &db.Common_nav{Id: 11, Parentid: 0, Name: "日志", Title: "Blog", Url: "home.php?mod=space&do=blog", Identifier: "12", Target: 0, Type: 0, Available: -1, Displayorder: 12, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[11] = &db.Common_nav{Id: 12, Parentid: 0, Name: "相册", Title: "Album", Url: "home.php?mod=space&do=album", Identifier: "13", Target: 0, Type: 0, Available: -1, Displayorder: 13, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[12] = &db.Common_nav{Id: 13, Parentid: 0, Name: "分享", Title: "Share", Url: "home.php?mod=space&do=share", Identifier: "14", Target: 0, Type: 0, Available: -1, Displayorder: 14, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[13] = &db.Common_nav{Id: 14, Parentid: 0, Name: "记录", Title: "Doing", Url: "home.php?mod=space&do=doing", Identifier: "15", Target: 0, Type: 0, Available: -1, Displayorder: 15, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 0, Logo: ""}
		data[14] = &db.Common_nav{Id: 15, Parentid: 0, Name: "站点统计", Title: "", Url: "misc.php?mod=stat", Identifier: "stat", Target: 0, Type: 0, Available: 1, Displayorder: 1, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 1, Logo: ""}
		data[15] = &db.Common_nav{Id: 16, Parentid: 0, Name: "举报", Title: "", Url: "#", Identifier: "report", Target: 0, Type: 0, Available: 1, Displayorder: 2, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 1, Logo: ""}
		data[16] = &db.Common_nav{Id: 17, Parentid: 0, Name: "Archiver", Title: "", Url: "archiver/", Identifier: "archiver", Target: 0, Type: 0, Available: 1, Displayorder: 3, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 1, Logo: ""}
		data[17] = &db.Common_nav{Id: 18, Parentid: 0, Name: "手机版", Title: "", Url: "forum.php?mobile=yes", Identifier: "mobile", Target: 0, Type: 0, Available: 1, Displayorder: 3, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 1, Logo: ""}
		data[18] = &db.Common_nav{Id: 19, Parentid: 0, Name: "小黑屋", Title: "", Url: "forum.php?mod=misc&action=showdarkroom", Identifier: "darkroom", Target: 0, Type: 0, Available: 1, Displayorder: 3, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 1, Logo: ""}
		data[19] = &db.Common_nav{Id: 20, Parentid: 0, Name: "日志", Title: "", Url: "home.php?mod=space&do=blog", Identifier: "blog", Target: 0, Type: 0, Available: -1, Displayorder: 2, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/blog.gif", Subname: "发布", Suburl: "home.php?mod=spacecp&ac=blog", Navtype: 2, Logo: ""}
		data[20] = &db.Common_nav{Id: 21, Parentid: 0, Name: "相册", Title: "", Url: "home.php?mod=space&do=album", Identifier: "album", Target: 0, Type: 0, Available: -1, Displayorder: 3, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/album.gif", Subname: "上传", Suburl: "home.php?mod=spacecp&ac=upload", Navtype: 2, Logo: ""}
		data[21] = &db.Common_nav{Id: 22, Parentid: 0, Name: "分享", Title: "", Url: "home.php?mod=space&do=share", Identifier: "share", Target: 0, Type: 0, Available: -1, Displayorder: 4, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/share.gif", Subname: "添加", Suburl: "home.php?mod=spacecp&ac=share", Navtype: 2, Logo: ""}
		data[22] = &db.Common_nav{Id: 23, Parentid: 0, Name: "记录", Title: "", Url: "home.php?mod=space&do=doing", Identifier: "doing", Target: 0, Type: 0, Available: -1, Displayorder: 5, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/doing.gif", Subname: "", Suburl: "", Navtype: 2, Logo: ""}
		data[23] = &db.Common_nav{Id: 24, Parentid: 0, Name: "广播", Title: "", Url: "home.php?mod=follow", Identifier: "follow", Target: 0, Type: 0, Available: -1, Displayorder: 6, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/follow.gif", Subname: "", Suburl: "", Navtype: 2, Logo: ""}
		data[24] = &db.Common_nav{Id: 25, Parentid: 0, Name: "{hr}", Title: "", Url: "", Identifier: "", Target: 0, Type: 1, Available: 1, Displayorder: 8, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 2, Logo: ""}
		data[25] = &db.Common_nav{Id: 26, Parentid: 0, Name: "好友", Title: "", Url: "home.php?mod=space&do=friend", Identifier: "friend", Target: 0, Type: 0, Available: 0, Displayorder: 1, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/friend_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[26] = &db.Common_nav{Id: 27, Parentid: 0, Name: "帖子", Title: "", Url: "forum.php?mod=guide&view=my", Identifier: "thread", Target: 0, Type: 0, Available: 0, Displayorder: 2, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/thread_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[27] = &db.Common_nav{Id: 28, Parentid: 0, Name: "收藏", Title: "", Url: "home.php?mod=space&do=favorite&view=me", Identifier: "favorite", Target: 0, Type: 0, Available: 0, Displayorder: 3, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/favorite_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[28] = &db.Common_nav{Id: 29, Parentid: 0, Name: "道具", Title: "", Url: "home.php?mod=magic", Identifier: "magic", Target: 0, Type: 0, Available: 1, Displayorder: 4, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/magic_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}

		data[29] = &db.Common_nav{Id: 30, Parentid: 0, Name: "勋章", Title: "", Url: "home.php?mod=medal", Identifier: "medal", Target: 0, Type: 0, Available: 1, Displayorder: 5, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/medal_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}

		data[30] = &db.Common_nav{Id: 31, Parentid: 0, Name: "任务", Title: "", Url: "home.php?mod=task", Identifier: "task", Target: 0, Type: 0, Available: 1, Displayorder: 6, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/task_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[31] = &db.Common_nav{Id: 32, Parentid: 0, Name: "淘帖", Title: "", Url: "forum.php?mod=collection&op=my", Identifier: "collection", Target: 0, Type: 0, Available: -1, Displayorder: 7, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/collection_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[32] = &db.Common_nav{Id: 33, Parentid: 0, Name: "动态", Title: "", Url: "home.php", Identifier: "feed", Target: 0, Type: 0, Available: -1, Displayorder: 8, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/feed_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[33] = &db.Common_nav{Id: 34, Parentid: 0, Name: "日志", Title: "", Url: "home.php?mod=space&do=blog", Identifier: "blog", Target: 0, Type: 0, Available: -1, Displayorder: 9, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/blog_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[34] = &db.Common_nav{Id: 35, Parentid: 0, Name: "相册", Title: "", Url: "home.php?mod=space&do=album", Identifier: "album", Target: 0, Type: 0, Available: -1, Displayorder: 10, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/album_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[35] = &db.Common_nav{Id: 36, Parentid: 0, Name: "分享", Title: "", Url: "home.php?mod=space&do=share", Identifier: "share", Target: 0, Type: 0, Available: -1, Displayorder: 11, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/share_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[36] = &db.Common_nav{Id: 37, Parentid: 0, Name: "记录", Title: "", Url: "home.php?mod=space&do=doing", Identifier: "doing", Target: 0, Type: 0, Available: -1, Displayorder: 12, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/doing_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[37] = &db.Common_nav{Id: 38, Parentid: 0, Name: "留言板", Title: "", Url: "home.php?mod=space&do=wall", Identifier: "wall", Target: 0, Type: 0, Available: -1, Displayorder: 13, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/wall_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[38] = &db.Common_nav{Id: 39, Parentid: 0, Name: "广播", Title: "", Url: "home.php?mod=follow", Identifier: "follow", Target: 0, Type: 0, Available: 1, Displayorder: 14, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/follow_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[39] = &db.Common_nav{Id: 40, Parentid: 0, Name: "群组", Title: "", Url: "group.php", Identifier: "group", Target: 0, Type: 0, Available: 0, Displayorder: 15, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/group_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[40] = &db.Common_nav{Id: 41, Parentid: 0, Name: "门户", Title: "", Url: "portal.php", Identifier: "portal", Target: 0, Type: 0, Available: 1, Displayorder: 16, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/portal_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[41] = &db.Common_nav{Id: 42, Parentid: 0, Name: "导读", Title: "", Url: "forum.php?mod=guide", Identifier: "guide", Target: 0, Type: 0, Available: -1, Displayorder: 17, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/guide_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[42] = &db.Common_nav{Id: 43, Parentid: 0, Name: "排行榜", Title: "", Url: "misc.php?mod=ranklist", Identifier: "ranklist", Target: 0, Type: 0, Available: -1, Displayorder: 18, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "{STATICURL}image/feed/ranklist_b.png", Subname: "", Suburl: "", Navtype: 3, Logo: ""}
		data[43] = &db.Common_nav{Id: 44, Parentid: 0, Name: "设为首页", Title: "", Url: "#", Identifier: "sethomepage", Target: 0, Type: 0, Available: 1, Displayorder: 1, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 4, Logo: ""}
		data[44] = &db.Common_nav{Id: 45, Parentid: 0, Name: "收藏本站", Title: "", Url: "#", Identifier: "setfavorite", Target: 0, Type: 0, Available: 1, Displayorder: 2, Highlight: 0, Level: 0, Subtype: 0, Subcols: 0, Icon: "", Subname: "", Suburl: "", Navtype: 4, Logo: ""}
		model.Table("Common_nav").InsertAll(data)
	}

}
