package models

import (
	"bbs/db"
	"sync"
)

type Model_usergroup struct {
	Model
}

var (
	usergroup_cache  sync.Map
	admingroup_cache sync.Map
)

func usergroup_init() {
	model := new(Model)
	c, _ := model.Table("Common_usergroup").Count()
	if c == 0 {
		var data = make([]*db.Common_usergroup, 11)
		data[0] = &db.Common_usergroup{Groupid: 1, Type: 1, Radminid: 1, System: "private", Grouptitle: "管理员", Stars: 9, Allowvisit: 1, Allowsendpm: 1, Allowinvite: 1, Allowmailinvite: 1, Maxinviteday: 10, Readaccess: 200, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowdirectpost: 3, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 127, Allowcstatus: true, Allowinvisible: 1, Allowtransfer: 1, Allowsetreadperm: true, Allowsetattachperm: true, Allowposttag: true, Allowhidecode: true, Allowhtml: true, Allowanonymous: true, Allowsigbbcode: true, Allowsigimgcode: true, Allowmagics: 2, Disableperiodctrl: 1, Maxprice: 30, Maxsigsize: 500, Maxattachsize: 2048000, Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 200, Allowpostdebate: true, Tradestick: 5, Exempt: 255, Allowposturl: 3, Allowrecommend: 1, Allowpostrushreply: true, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowstat: 1, Allowstatdata: 1, Videophotoignore: 1, Allowviewvideophoto: 1, Allowmyop: 1, Domainlength: 5, Seccode: 1, Disablepostctrl: true, Allowbuildgroup: 30, Allowgroupdirectpost: 3, Allowgroupposturl: 3, Allowpostarticle: true, Allowdownlocalimg: 1, Allowdownremoteimg: true, Allowspacediyhtml: 1, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 3, Allowcommentitem: 1, Allowreplycredit: true, Ignorecensor: 1, Allowsendallpm: 1, Allowmediacode: true, Allowbegincode: true, Allowat: 50, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		data[1] = &db.Common_usergroup{Groupid: 2, Type: 1, Radminid: 2, System: "private", Grouptitle: "超级版主", Stars: 8, Allowvisit: 1, Allowsendpm: 1, Allowinvite: 1, Allowmailinvite: 1, Maxinviteday: 10, Readaccess: 150, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowdirectpost: 3, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowcstatus: true, Allowinvisible: 1, Allowtransfer: 1, Allowsetreadperm: true, Allowsetattachperm: true, Allowhidecode: true, Allowanonymous: true, Allowsigbbcode: true, Allowsigimgcode: true, Allowmagics: 2, Disableperiodctrl: 1, Maxprice: 20, Maxsigsize: 300, Maxattachsize: 2048000, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 180, Allowpostdebate: true, Tradestick: 5, Exempt: 255, Allowposturl: 3, Allowrecommend: 1, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Domainlength: 5, Seccode: 1, Disablepostctrl: true, Allowbuildgroup: 20, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowreplycredit: true, Ignorecensor: 1, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		data[2] = &db.Common_usergroup{Groupid: 3, Type: 1, Radminid: 3, System: "private", Grouptitle: "版主", Stars: 7, Allowvisit: 1, Allowsendpm: 1, Allowinvite: 1, Allowmailinvite: 1, Maxinviteday: 10, Readaccess: 100, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowdirectpost: 1, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowcstatus: true, Allowtransfer: 1, Allowsetreadperm: true, Allowsetattachperm: true, Allowhidecode: true, Allowsigbbcode: true, Allowsigimgcode: true, Allowmagics: 2, Disableperiodctrl: 1, Maxprice: 10, Maxsigsize: 200, Maxattachsize: 2048000, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 160, Allowpostdebate: true, Tradestick: 5, Exempt: 224, Allowposturl: 3, Allowrecommend: 1, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Domainlength: 5, Seccode: 1, Disablepostctrl: true, Allowbuildgroup: 15, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowreplycredit: true, Ignorecensor: 1, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		data[3] = &db.Common_usergroup{Groupid: 4, Type: 2, System: "private", Grouptitle: "禁止发言", Allowvisit: 1, Allowsendpm: 1, Mintradeprice: 1, Minrewardprice: 1, Tradestick: 5, Allowposturl: 3, Allowrecommend: 1, Seccode: 1, Allowgroupdirectpost: 3}
		data[4] = &db.Common_usergroup{Groupid: 5, Type: 2, System: "private", Grouptitle: "禁止访问", Allowsendpm: 1, Mintradeprice: 1, Minrewardprice: 1, Tradestick: 5, Allowposturl: 3, Allowrecommend: 1, Seccode: 1, Allowgroupdirectpost: 3}
		data[5] = &db.Common_usergroup{Groupid: 6, Type: 2, System: "private", Grouptitle: "禁止 IP", Allowsendpm: 1, Mintradeprice: 1, Minrewardprice: 1, Tradestick: 5, Allowposturl: 3, Allowrecommend: 1, Seccode: 1, Allowgroupdirectpost: 3}
		data[6] = &db.Common_usergroup{Groupid: 7, Type: 2, System: "private", Grouptitle: "游客", Allowvisit: 1, Allowsendpm: 1, Maxinviteday: 10, Readaccess: 1, Allowsearch: 19, Attachextensions: "gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Tradestick: 5, Allowposturl: 3, Allowmyop: 1, Seccode: 1, Allowgroupdirectpost: 3}
		data[7] = &db.Common_usergroup{Groupid: 8, Type: 2, System: "private", Grouptitle: "等待验证会员", Allowvisit: 1, Allowsendpm: 1, Allowsearch: 2, Allowsigbbcode: true, Maxsigsize: 50, Mintradeprice: 1, Minrewardprice: 1, Tradestick: 5, Allowposturl: 3, Allowrecommend: 1, Seccode: 1, Allowgroupdirectpost: 3, Allowcommentpost: 2}
		data[8] = &db.Common_usergroup{Groupid: 9, Type: 3, System: "private", Grouptitle: "注册会员", Creditshigher: -9999999, Creditslower: 9999999, Stars: 2, Allowvisit: 1, Allowsendpm: 1, Maxinviteday: 10, Readaccess: 20, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowsigbbcode: true, Allowmagics: 1, Maxsigsize: 100, Maxattachsize: 1024000, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 60, Allowpostdebate: true, Tradestick: 5, Allowposturl: 3, Allowrecommend: 1, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Domainlength: 5, Seccode: 1, Allowbuildgroup: 5, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowreplycredit: true, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		data[9] = &db.Common_usergroup{Groupid: 10, Type: 1, Radminid: 3, System: "private", Grouptitle: "实习版主", Stars: 7, Allowvisit: 1, Allowsendpm: 1, Maxinviteday: 10, Readaccess: 100, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowdirectpost: 1, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowcstatus: true, Allowtransfer: 1, Allowsetreadperm: true, Allowsetattachperm: true, Allowhidecode: true, Allowsigbbcode: true, Allowsigimgcode: true, Allowmagics: 2, Disableperiodctrl: 1, Maxprice: 10, Maxsigsize: 200, Maxattachsize: 2048000, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 160, Allowpostdebate: true, Tradestick: 5, Exempt: 188, Allowposturl: 3, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Domainlength: 5, Seccode: 1, Allowbuildgroup: 15, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowreplycredit: true, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		data[10] = &db.Common_usergroup{Groupid: 11, Type: 3, System: "private", Grouptitle: "测试会员", Creditshigher: -9999999, Allowvisit: 1, Allowsendpm: 1, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png ", Mintradeprice: 1, Minrewardprice: 1, Magicsdiscount: 1, Tradestick: 5, Seccode: 1, Allowcommentitem: 1, Allowpostimage: true, Maxattachnum: 1, Maxsizeperday: 1, Allowpost: true}
		//data[11] = &db.Common_usergroup{Groupid: 12, Type: 3, System: "private", Grouptitle: "限制会员", Creditshigher: -9999999, Allowvisit: 1, Allowsendpm: 1, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png ", Mintradeprice: 1, Minrewardprice: 1, Magicsdiscount: 1, Tradestick: 5, Seccode: 1, Allowcommentitem: 1}
		//data[12] = &db.Common_usergroup{Groupid: 13, Type: 3, System: "private", Grouptitle: "新手上路", Creditslower: 50, Stars: 1, Allowvisit: 1, Allowsendpm: 1, Maxinviteday: 10, Readaccess: 10, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowsigbbcode: true, Allowmagics: 1, Maxsigsize: 80, Maxattachsize: 1024000, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 40, Allowpostdebate: true, Tradestick: 5, Allowposturl: 3, Allowrecommend: 1, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Domainlength: 5, Seccode: 1, Allowbuildgroup: 5, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		//data[13] = &db.Common_usergroup{Groupid: 14, Type: 3, System: "private", Grouptitle: "中级会员", Creditshigher: 200, Creditslower: 500, Stars: 3, Allowvisit: 1, Allowsendpm: 1, Maxinviteday: 10, Readaccess: 30, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowsigbbcode: true, Allowmagics: 1, Maxsigsize: 150, Maxattachsize: 1024000, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 80, Allowpostdebate: true, Tradestick: 5, Allowposturl: 3, Allowrecommend: 1, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Domainlength: 5, Seccode: 1, Allowbuildgroup: 5, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowreplycredit: true, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		//data[14] = &db.Common_usergroup{Groupid: 15, Type: 3, System: "private", Grouptitle: "高级会员", Creditshigher: 500, Creditslower: 1000, Stars: 4, Allowvisit: 1, Allowsendpm: 1, Maxinviteday: 10, Readaccess: 50, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowcstatus: true, Allowsigbbcode: true, Allowmagics: 2, Maxsigsize: 200, Maxattachsize: 2048000, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 100, Allowpostdebate: true, Tradestick: 5, Allowposturl: 3, Allowrecommend: 1, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Seccode: 1, Allowbuildgroup: 10, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowreplycredit: true, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		//data[15] = &db.Common_usergroup{Groupid: 16, Type: 3, System: "private", Grouptitle: "金牌会员", Creditshigher: 1000, Creditslower: 3000, Stars: 6, Allowvisit: 1, Allowsendpm: 1, Maxinviteday: 10, Readaccess: 70, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowcstatus: true, Allowsetreadperm: true, Allowsetattachperm: true, Allowsigbbcode: true, Allowsigimgcode: true, Allowmagics: 2, Maxsigsize: 300, Maxattachsize: 2048000, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 120, Allowpostdebate: true, Tradestick: 5, Allowposturl: 3, Allowrecommend: 1, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Domainlength: 5, Seccode: 1, Allowbuildgroup: 10, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowreplycredit: true, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		//data[16] = &db.Common_usergroup{Groupid: 17, Type: 3, System: "private", Grouptitle: "论坛元老", Creditshigher: 3000, Creditslower: 9999999, Stars: 8, Allowvisit: 1, Allowsendpm: 1, Maxinviteday: 10, Readaccess: 90, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowcstatus: true, Allowinvisible: 1, Allowsetreadperm: true, Allowsetattachperm: true, Allowanonymous: true, Allowsigbbcode: true, Allowsigimgcode: true, Allowmagics: 2, Maxsigsize: 500, Maxattachsize: 2048000, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 140, Allowpostdebate: true, Tradestick: 5, Allowposturl: 3, Allowrecommend: 1, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Domainlength: 5, Seccode: 1, Allowbuildgroup: 10, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowreplycredit: true, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		//data[17] = &db.Common_usergroup{Groupid: 18, Type: 2, Radminid: 2, System: "private", Grouptitle: "网站编辑", Stars: 8, Allowvisit: 1, Allowsendpm: 1, Maxinviteday: 10, Readaccess: 150, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowdirectpost: 3, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowcstatus: true, Allowinvisible: 1, Allowtransfer: 1, Allowsetreadperm: true, Allowsetattachperm: true, Allowhidecode: true, Allowsigbbcode: true, Allowsigimgcode: true, Allowmagics: 2, Disableperiodctrl: 1, Maxprice: 20, Maxsigsize: 300, Maxattachsize: 2048000, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 180, Allowpostdebate: true, Tradestick: 5, Exempt: 255, Allowposturl: 3, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Domainlength: 5, Seccode: 1, Disablepostctrl: true, Allowbuildgroup: 15, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowreplycredit: true, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		//data[18] = &db.Common_usergroup{Groupid: 19, Type: 2, Radminid: 1, System: "private", Grouptitle: "信息监察员", Stars: 9, Allowvisit: 1, Allowsendpm: 1, Maxinviteday: 10, Readaccess: 200, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowdirectpost: 3, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowinvisible: 1, Allowtransfer: 1, Allowsetreadperm: true, Allowsetattachperm: true, Allowhidecode: true, Allowhtml: true, Allowanonymous: true, Allowsigbbcode: true, Allowsigimgcode: true, Allowmagics: 2, Maxprice: 30, Maxsigsize: 500, Maxpostsperhour: 1, Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 200, Allowpostdebate: true, Tradestick: 5, Exempt: 255, Allowposturl: 3, Allowrecommend: 3, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Domainlength: 15, Seccode: 1, Disablepostctrl: true, Allowbuildgroup: 5, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowreplycredit: true, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		//data[19] = &db.Common_usergroup{Groupid: 20, Type: 2, Radminid: 3, System: "private", Grouptitle: "审核员", Stars: 7, Allowvisit: 1, Allowsendpm: 1, Maxinviteday: 10, Readaccess: 100, Allowpost: true, Allowreply: true, Allowpostpoll: true, Allowpostreward: true, Allowposttrade: true, Allowpostactivity: true, Allowdirectpost: 1, Allowgetattach: true, Allowgetimage: true, Allowpostattach: true, Allowpostimage: true, Allowvote: true, Allowsearch: 95, Allowcstatus: true, Allowtransfer: 1, Allowsetreadperm: true, Allowsetattachperm: true, Allowhidecode: true, Allowsigbbcode: true, Allowsigimgcode: true, Allowmagics: 2, Disableperiodctrl: 1, Maxprice: 10, Maxsigsize: 200, Maxattachsize: 2048000, Attachextensions: "chm,pdf,zip,rar,tar,gz,bzip2,gif,jpg,jpeg,png", Mintradeprice: 1, Minrewardprice: 1, Maxmagicsweight: 160, Allowpostdebate: true, Tradestick: 5, Exempt: 188, Allowposturl: 3, Allowcomment: 1, Allowcommentarticle: 1000, Allowblog: 1, Allowdoing: 1, Allowupload: true, Allowshare: 1, Allowpoke: 1, Allowfriend: 1, Allowclick: 1, Allowmyop: 1, Domainlength: 5, Seccode: 1, Disablepostctrl: true, Allowbuildgroup: 15, Allowgroupdirectpost: 3, Allowspacediybbcode: 1, Allowspacediyimgcode: 1, Allowcommentpost: 2, Allowcommentitem: 1, Allowreplycredit: true, Allowfollowcollection: 30, Allowcommentcollection: 1, Allowcreatecollection: 5}
		model.Table("Common_usergroup").InsertAll(data)
		var admin_data = make([]*db.Common_admingroup, 7)
		admin_data[0] = &db.Common_admingroup{Admingid: 1, Alloweditpost: true, Alloweditpoll: true, Allowstickthread: 3, Allowmodpost: 1, Allowdelpost: true, Allowmassprune: 1, Allowrefund: 1, Allowcensorword: 1, Allowviewip: true, Allowbanip: 1, Allowedituser: true, Allowmoduser: 1, Allowbanuser: true, Allowbanvisituser: 1, Allowpostannounce: 1, Allowviewlog: 1, Allowbanpost: true, Supe_allowpushthread: 1, Allowhighlightthread: true, Allowlivethread: 1, Allowdigestthread: 3, Allowrecommendthread: true, Allowbumpthread: true, Allowclosethread: true, Allowmovethread: true, Allowedittypethread: true, Allowstampthread: true, Allowstamplist: true, Allowcopythread: true, Allowmergethread: true, Allowsplitthread: true, Allowrepairthread: true, Allowwarnpost: true, Allowviewreport: 1, Alloweditforum: 1, Allowremovereward: true, Allowedittrade: 1, Alloweditactivity: 1, Allowstickreply: true, Allowmanagearticle: true, Allowaddtopic: true, Allowmanagetopic: true, Allowdiy: true, Allowclearrecycle: true, Allowmanagetag: true, Managefeed: 1, Managedoing: 1, Manageshare: 1, Manageblog: 1, Managealbum: 1, Managecomment: 1, Managemagiclog: 1, Managereport: 1, Managehotuser: 1, Managedefaultuser: 1, Managevideophoto: 1, Managemagic: 1, Manageclick: 1, Allowmanagecollection: 1, Allowmakehtml: 1}
		admin_data[1] = &db.Common_admingroup{Admingid: 2, Alloweditpost: true, Allowstickthread: 2, Allowmodpost: 1, Allowdelpost: true, Allowmassprune: 1, Allowrefund: 1, Allowcensorword: 1, Allowviewip: true, Allowbanip: 1, Allowedituser: true, Allowmoduser: 1, Allowbanuser: true, Allowbanvisituser: 1, Allowpostannounce: 1, Allowviewlog: 1, Allowbanpost: true, Supe_allowpushthread: 0, Allowhighlightthread: true, Allowlivethread: 1, Allowdigestthread: 3, Allowrecommendthread: true, Allowbumpthread: true, Allowclosethread: true, Allowmovethread: true, Allowedittypethread: true, Allowstampthread: true, Allowstamplist: true, Allowcopythread: true, Allowmergethread: true, Allowsplitthread: true, Allowrepairthread: true, Allowwarnpost: true, Allowviewreport: 1, Alloweditforum: 1, Allowremovereward: true, Allowmanagecollection: 1}
		admin_data[2] = &db.Common_admingroup{Admingid: 3, Alloweditpost: true, Allowstickthread: 1, Allowmodpost: 1, Allowdelpost: true, Allowviewip: true, Allowmoduser: 1, Allowbanuser: true, Allowviewlog: 1, Allowbanpost: true, Supe_allowpushthread: 0, Allowhighlightthread: true, Allowlivethread: 1, Allowdigestthread: 3, Allowrecommendthread: true, Allowbumpthread: true, Allowclosethread: true, Allowmovethread: true, Allowedittypethread: true, Allowstampthread: true, Allowstamplist: true, Allowcopythread: true, Allowmergethread: true, Allowsplitthread: true, Allowrepairthread: true, Allowwarnpost: true, Allowviewreport: 1, Alloweditforum: 1, Allowremovereward: true}
		//admin_data[3] = &db.Common_admingroup{Admingid: 16, Allowstickthread: 1, Allowbanpost: true, Supe_allowpushthread: 0, Allowhighlightthread: true, Allowdigestthread: 1, Allowrecommendthread: true, Allowbumpthread: true, Allowclosethread: true, Allowstampthread: true, Allowwarnpost: true, Allowviewreport: 1}
		//admin_data[4] = &db.Common_admingroup{Admingid: 17, Alloweditpost: true, Allowstickthread: 2, Allowmodpost: 1, Allowrefund: 1, Allowviewip: true, Allowpostannounce: 1, Allowviewlog: 1, Allowbanpost: true, Supe_allowpushthread: 0, Allowhighlightthread: true, Allowdigestthread: 3, Allowrecommendthread: true, Allowbumpthread: true, Allowclosethread: true, Allowmovethread: true, Allowedittypethread: true, Allowstampthread: true, Allowcopythread: true, Allowmergethread: true, Allowsplitthread: true, Allowrepairthread: true, Allowwarnpost: true, Allowviewreport: 1, Alloweditforum: 1, Allowremovereward: true}
		//admin_data[5] = &db.Common_admingroup{Admingid: 18, Allowviewip: true, Supe_allowpushthread: 1}
		//admin_data[6] = &db.Common_admingroup{Admingid: 19, Allowmodpost: 1, Allowviewip: true, Allowbanip: 1, Allowmoduser: 1, Allowbanuser: true, Supe_allowpushthread: 0}
		model.Table("Common_admingroup").InsertAll(admin_data)
		/*var groupicon = make([]*db.Forum_onlinelist, 4)
		groupicon[0] = &db.Forum_onlinelist{Groupid: 1, Displayorder: 1, Title: "管理员", Url: "online_admin.gif"}
		groupicon[1] = &db.Forum_onlinelist{Groupid: 2, Displayorder: 2, Title: "超级版主", Url: "online_supermod.gif"}
		groupicon[2] = &db.Forum_onlinelist{Groupid: 3, Displayorder: 3, Title: "版主", Url: "online_moderator.gif"}
		groupicon[3] = &db.Forum_onlinelist{Groupid: 0, Displayorder: 4, Title: "会员", Url: "online_member.gif"}
		model.Table("Forum_onlinelist").InsertAll(groupicon)*/
	}

	var data1 []*db.Common_usergroup
	model.Table("Common_usergroup").Limit(0).Select(&data1)
	for _, v := range data1 {
		usergroup_cache.Store(v.Groupid, v)
	}
	var data2 []*db.Common_admingroup
	model.Table("Common_admingroup").Limit(0).Select(&data2)
	for _, v := range data2 {
		admingroup_cache.Store(v.Admingid, v)
	}
}
func (*Model_usergroup) GetUserGroupByID(groupid int16) *db.Common_usergroup {
	if v, ok := usergroup_cache.Load(groupid); ok {
		return v.(*db.Common_usergroup)
	}
	return nil
}
func (*Model_usergroup) GetMemberGroupIDFromCredits(credits int32) (group *db.Common_usergroup) {
	usergroup_cache.Range(func(k, v interface{}) bool {
		g := v.(*db.Common_usergroup)
		if g.Type == 3 && credits >= g.Creditshigher && credits < g.Creditslower {
			group = g
			return false
		}
		return true
	})
	return group
}
func (m *Model_usergroup) GetNextCreditsByCredits(credits int32) (upgradecredit int32) {
	oldgroup := m.GetMemberGroupIDFromCredits(credits)
	if oldgroup == nil {
		return
	}
	var group *db.Common_usergroup
	usergroup_cache.Range(func(k, v interface{}) bool {
		group = v.(*db.Common_usergroup)
		if group.Type == 3 && group.Stars == oldgroup.Stars+1 {
			return false
		}
		return true
	})
	if group != nil {
		return group.Creditshigher - credits
	}
	return
}
func (*Model_usergroup) GetForumGroup() (group []*db.Common_usergroup) {
	usergroup_cache.Range(func(k, v interface{}) bool {
		g := v.(*db.Common_usergroup)
		if g.Radminid == 3 {
			group = append(group, g)
		}
		return true

	})
	return group
}
func (*Model_usergroup) GetAllGroup() sync.Map {
	return usergroup_cache
}
func (*Model_usergroup) GetAdminGroupByAdminID(adminid int16) *db.Common_admingroup {
	if v, ok := admingroup_cache.Load(adminid); ok {
		return v.(*db.Common_admingroup)
	}
	return nil
}
